/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#6ff6ff",
        "on-primary": "#00373a",
        "inverse-surface": "#dde2f1",
        "on-error": "#690005",
        "tertiary-container": "#d6dbea",
        "error-container": "#93000a",
        "surface-variant": "#2f3540",
        "secondary": "#ddb7ff",
        "surface-container-lowest": "#080e18",
        "on-background": "#dde2f1",
        "error": "#ffb4ab",
        "background": "#0e131e",
        "tertiary-fixed": "#dde2f1",
        "outline-variant": "#3a494b",
        "on-tertiary-fixed": "#161c26",
        "surface-container-highest": "#2f3540",
        "on-secondary": "#4a0080",
        "on-secondary-fixed": "#2c0050",
        "on-tertiary": "#2b313c",
        "inverse-primary": "#00696f",
        "primary": "#e0fdff",
        "secondary-container": "#7900cd",
        "secondary-fixed": "#f0dbff",
        "surface-container-high": "#242a35",
        "surface-dim": "#0e131e",
        "outline": "#849495",
        "on-secondary-container": "#ddb7ff",
        "on-tertiary-container": "#5a606d",
        "on-primary-container": "#006a70",
        "surface-container-low": "#161c26",
        "on-secondary-fixed-variant": "#6900b3",
        "tertiary": "#f7f7ff",
        "on-primary-fixed-variant": "#004f53",
        "inverse-on-surface": "#2b313c",
        "on-primary-fixed": "#002022",
        "on-tertiary-fixed-variant": "#414753",
        "primary-fixed-dim": "#00dce6",
        "tertiary-fixed-dim": "#c1c6d5",
        "on-surface-variant": "#b9cacb",
        "surface": "#0e131e",
        "secondary-fixed-dim": "#ddb7ff",
        "surface-container": "#1a202a",
        "primary-container": "#00f2fe",
        "on-error-container": "#ffdad6",
        "on-surface": "#dde2f1",
        "surface-tint": "#00dce6",
        "surface-bright": "#343945"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}
