/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#2c3951",
        "surface-tint": "#b9c7e4",
        "on-primary-fixed-variant": "#39475f",
        "tertiary": "#b9c8de",
        "primary-fixed": "#d6e3ff",
        "error": "#ffb4ab",
        "surface-container-highest": "#27354c",
        "outline": "#8f9097",
        "inverse-on-surface": "#233148",
        "error-container": "#93000a",
        "surface-container": "#112036",
        "on-tertiary-fixed-variant": "#39485a",
        "on-tertiary-fixed": "#0d1c2d",
        "tertiary-container": "#0a1a2a",
        "on-secondary": "#00382d",
        "secondary-container": "#00c7a5",
        "on-primary-fixed": "#0d1c32",
        "surface-container-high": "#1c2a41",
        "primary": "#b9c7e4",
        "surface-dim": "#041329",
        "surface-container-low": "#0d1c32",
        "secondary-fixed-dim": "#38debb",
        "on-secondary-fixed-variant": "#005142",
        "on-primary": "#233148",
        "on-secondary-container": "#004d3f",
        "primary-container": "#0a192f",
        "inverse-primary": "#515f78",
        "on-primary-container": "#74829d",
        "outline-variant": "#44474d",
        "tertiary-fixed": "#d4e4fa",
        "on-background": "#d6e3ff",
        "on-surface": "#d6e3ff",
        "on-secondary-fixed": "#002019",
        "on-tertiary-container": "#748397",
        "secondary-fixed": "#5ffbd6",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#b9c8de",
        "on-surface-variant": "#c5c6cd",
        "primary-fixed-dim": "#b9c7e4",
        "on-error": "#690005",
        "background": "#041329",
        "surface-variant": "#27354c",
        "secondary": "#41e4c0",
        "inverse-surface": "#d6e3ff",
        "surface": "#041329",
        "surface-container-lowest": "#010e24",
        "on-tertiary": "#233143"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}
